const configs = {
  /**
   * Mercury
   */
  mer: {
    uBaseAtmosMix: 0,
    uBloomIntensity: 2.5,
    uColor1: "#ccd1bc",
    uColor2: "#ccd1bc",
    uColor3: "#ccd1bc",
    uColor4: "#ccd1bc",
    uColorAtmos1: "#000000",
    uColorAtmos2: "#82e3ff",
    uFresnelAmount: 0,
    uFresnelPower: 2,
    uFresnelColor: "#ffffff",
    uScale: 0.3,
    uScaleX: 0.1,
    uScaleY: 17,
    uScaleAtmos: 0.7,
    uScaleAtmosX: 0.2,
    uScaleAtmosY: 20,
    uSeed: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinX: 0.5,
    uSpinY: 0,
    uSeedAtmos: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinAtmosX: -0.5,
    uSpinAtmosY: 0,
    uStop1: 0,
    uStop2: 0.3,
    uStop3: 0.5,
    uStop4: 0.7,
    uStopAtmos1: 0.4,
    uStopAtmos2: 0.6,
    uTimeMult: 0.2,
    uTimeMultAtmos: 0.2,
  },
  /**
   * Venus
   */
  ven: {
    uBaseAtmosMix: 0,
    uBloomIntensity: 2.5,
    uColor1: "#8398aa",
    uColor2: "#8398aa",
    uColor3: "#8398aa",
    uColor4: "#8398aa",
    uColorAtmos1: "#000000",
    uColorAtmos2: "#82e3ff",
    uFresnelAmount: 0,
    uFresnelPower: 2,
    uFresnelColor: "#ffffff",
    uScale: 0.3,
    uScaleX: 0.1,
    uScaleY: 17,
    uScaleAtmos: 0.7,
    uScaleAtmosX: 0.2,
    uScaleAtmosY: 20,
    uSeed: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinX: 0.5,
    uSpinY: 0,
    uSeedAtmos: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinAtmosX: -0.5,
    uSpinAtmosY: 0,
    uStop1: 0,
    uStop2: 0.3,
    uStop3: 0.5,
    uStop4: 0.7,
    uStopAtmos1: 0.4,
    uStopAtmos2: 0.6,
    uTimeMult: 0.2,
    uTimeMultAtmos: 0.2,
  },
  /**
   * Earth
   */
  ear: {
    uBaseAtmosMix: 0,
    uBloomIntensity: 2.5,
    uColor1: "#3f6aeb",
    uColor2: "#3f6aeb",
    uColor3: "#3f6aeb",
    uColor4: "#3f6aeb",
    uColorAtmos1: "#000000",
    uColorAtmos2: "#82e3ff",
    uFresnelAmount: 0,
    uFresnelPower: 2,
    uFresnelColor: "#ffffff",
    uScale: 0.3,
    uScaleX: 0.1,
    uScaleY: 17,
    uScaleAtmos: 0.7,
    uScaleAtmosX: 0.2,
    uScaleAtmosY: 20,
    uSeed: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinX: 0.5,
    uSpinY: 0,
    uSeedAtmos: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinAtmosX: -0.5,
    uSpinAtmosY: 0,
    uStop1: 0,
    uStop2: 0.3,
    uStop3: 0.5,
    uStop4: 0.7,
    uStopAtmos1: 0.4,
    uStopAtmos2: 0.6,
    uTimeMult: 0.2,
    uTimeMultAtmos: 0.2,
  },
  /**
   * Mars
   */
  mar: {
    uBaseAtmosMix: 0,
    uBloomIntensity: 2.5,
    uColor1: "#db2121",
    uColor2: "#db2121",
    uColor3: "#db2121",
    uColor4: "#db2121",
    uColorAtmos1: "#000000",
    uColorAtmos2: "#82e3ff",
    uFresnelAmount: 0,
    uFresnelPower: 2,
    uFresnelColor: "#ffffff",
    uScale: 0.3,
    uScaleX: 0.1,
    uScaleY: 17,
    uScaleAtmos: 0.7,
    uScaleAtmosX: 0.2,
    uScaleAtmosY: 20,
    uSeed: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinX: 0.5,
    uSpinY: 0,
    uSeedAtmos: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinAtmosX: -0.5,
    uSpinAtmosY: 0,
    uStop1: 0,
    uStop2: 0.3,
    uStop3: 0.5,
    uStop4: 0.7,
    uStopAtmos1: 0.4,
    uStopAtmos2: 0.6,
    uTimeMult: 0.2,
    uTimeMultAtmos: 0.2,
  },
  /**
   * Jupiter
   */
  jup: {
    uBaseAtmosMix: 0,
    uBloomIntensity: 2.5,
    uColor1: "#ff6900",
    uColor2: "#ff6900",
    uColor3: "#ff6900",
    uColor4: "#ff6900",
    uColorAtmos1: "#000000",
    uColorAtmos2: "#82e3ff",
    uFresnelAmount: 0,
    uFresnelPower: 2,
    uFresnelColor: "#ffffff",
    uScale: 0.3,
    uScaleX: 0.1,
    uScaleY: 17,
    uScaleAtmos: 0.7,
    uScaleAtmosX: 0.2,
    uScaleAtmosY: 20,
    uSeed: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinX: 0.5,
    uSpinY: 0,
    uSeedAtmos: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinAtmosX: -0.5,
    uSpinAtmosY: 0,
    uStop1: 0,
    uStop2: 0.3,
    uStop3: 0.5,
    uStop4: 0.7,
    uStopAtmos1: 0.4,
    uStopAtmos2: 0.6,
    uTimeMult: 0.2,
    uTimeMultAtmos: 0.2,
  },
  /**
   * Saturn
   */
  sat: {
    uBaseAtmosMix: 0,
    uBloomIntensity: 2.5,
    uColor1: "#8d89e2",
    uColor2: "#8d89e2",
    uColor3: "#8d89e2",
    uColor4: "#8d89e2",
    uColorAtmos1: "#000000",
    uColorAtmos2: "#82e3ff",
    uFresnelAmount: 0,
    uFresnelPower: 2,
    uFresnelColor: "#ffffff",
    uScale: 0.3,
    uScaleX: 0.1,
    uScaleY: 17,
    uScaleAtmos: 0.7,
    uScaleAtmosX: 0.2,
    uScaleAtmosY: 20,
    uSeed: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinX: 0.5,
    uSpinY: 0,
    uSeedAtmos: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinAtmosX: -0.5,
    uSpinAtmosY: 0,
    uStop1: 0,
    uStop2: 0.3,
    uStop3: 0.5,
    uStop4: 0.7,
    uStopAtmos1: 0.4,
    uStopAtmos2: 0.6,
    uTimeMult: 0.2,
    uTimeMultAtmos: 0.2,
  },
  /**
   * Uranus
   */
  ura: {
    uBaseAtmosMix: 0,
    uBloomIntensity: 2.5,
    uColor1: "#5e7f93",
    uColor2: "#5e7f93",
    uColor3: "#5e7f93",
    uColor4: "#5e7f93",
    uColorAtmos1: "#000000",
    uColorAtmos2: "#82e3ff",
    uFresnelAmount: 0,
    uFresnelPower: 2,
    uFresnelColor: "#ffffff",
    uScale: 0.3,
    uScaleX: 0.1,
    uScaleY: 17,
    uScaleAtmos: 0.7,
    uScaleAtmosX: 0.2,
    uScaleAtmosY: 20,
    uSeed: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinX: 0.5,
    uSpinY: 0,
    uSeedAtmos: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinAtmosX: -0.5,
    uSpinAtmosY: 0,
    uStop1: 0,
    uStop2: 0.3,
    uStop3: 0.5,
    uStop4: 0.7,
    uStopAtmos1: 0.4,
    uStopAtmos2: 0.6,
    uTimeMult: 0.2,
    uTimeMultAtmos: 0.2,
  },
  /**
   * Neptune
   */
  nep: {
    uBaseAtmosMix: 1.3,
    uBloomIntensity: 2.5,
    uColor1: "#00ffec",
    uColor2: "#00ffec",
    uColor3: "#00ffec",
    uColor4: "#00ffec",
    uColorAtmos1: "#000000",
    uColorAtmos2: "#82e3ff",
    uFresnelAmount: 0,
    uFresnelPower: 2,
    uFresnelColor: "#ffffff",
    uScale: 0.3,
    uScaleX: 0.1,
    uScaleY: 17,
    uScaleAtmos: 0.7,
    uScaleAtmosX: 0.2,
    uScaleAtmosY: 20,
    uSeed: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinX: 0.5,
    uSpinY: 0,
    uSeedAtmos: {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
    },
    uSpinAtmosX: -0.5,
    uSpinAtmosY: 0,
    uStop1: 0,
    uStop2: 0.3,
    uStop3: 0.5,
    uStop4: 0.7,
    uStopAtmos1: 0.4,
    uStopAtmos2: 0.6,
    uTimeMult: 0.2,
    uTimeMultAtmos: 0.2,
  },
};

export default function getPlanetConfig(planet) {
  // Get the config for the planet, return with keys prefixed with planet key underscore (mer_)
  return Object.entries(configs[planet]).reduce((acc, [key, value]) => {
    acc[`${planet}_${key}`] = value;
    return acc;
  }, {});
}
